tasks:
  - name: run wasmcloud_host
    init: cd wasmcloud_host && make build
    command: make run
  - name: run host_core
    init: cd host_core && make build
    command: make run
  - name: run local nats
    init: docker-compose -f .gitpod/docker-compose.yml pull
    command: docker-compose -f .gitpod/docker-compose.yml up

image:
  file: .gitpod.Dockerfile
  
github:
  prebuilds:
    addBadge: true
    branches: true
    master: true
    pullRequests: true

vscode:
  extensions:
    - "elixir-lsp.elixir-ls"